---
user: xes
gpg_keynum: 96915FFD
crypted_password: "{{ SECRET_plaintext_password | password_hash('sha512') }}"
ansible_sudo_pass: "{{ SECRET_plaintext_password }}"
pushbullet_api_key: "{{ SECRET_pushbullet_api_key }}"
bitbucket_deploy_key: "{{ SECRET_bitbucket_deploy_key }}"
