---
user: "xes"
gpg_keynum: "96915FFD"
php_version: "7.0"
crypted_password: "{{ SECRET_plaintext_password | password_hash('sha512') }}"
ci_crypted_password: "{{ SECRET_ci_plaintext_password | password_hash('sha512') }}"
ansible_sudo_pass: "{{ SECRET_plaintext_password }}"
pushbullet_api_key: "{{ SECRET_pushbullet_api_key }}"
ci_deploy_pub: "{{ SECRET_ci_deploy_pub }}"
newrelic_license_key: "{{ SECRET_newrelic_license_key }}"
mysql_root_password: "{{ SECRET_mysql_root_password }}"
mysql_backup:
  - {
      name: "backup",
      password: "{{ SECRET_mysql_backup_password }}",
    }
mysql_users: "{{ SECRET_mysql_users }}"
mysql_edit_perms: "{{ SECRET_mysql_edit_perms }}"
mysql_view_perms: "{{ SECRET_mysql_view_perms }}"
