---
- name: Enable bash colours
  template:
    src='bashrc.j2'
    dest='/home/{{user}}/.bashrc'
    owner='{{user}}'
    group='{{user}}'

- name: Enable bash aliases
  copy:
    src='bash_aliases'
    dest='/home/{{user}}/.bash_aliases'
    owner='{{user}}'
    group='{{user}}'

- name: Disable legal
  file:
    path='/etc/legal'
    state='absent'

- name: Copy custom MOTD
  template:
    src='motd.j2'
    dest='/etc/motd'
    owner='root'
    group='root'
    mode=0755
  notify:
    - Rebuild MOTD

- name: Register contents of MOTDs
  shell: 'ls -1 /etc/update-motd.d'
  register: contents
  changed_when: False

- name: Disable all MOTDs
  file:
    path='/etc/update-motd.d/{{item}}'
    mode='0644'
    follow='yes'
  with_items: '{{contents.stdout_lines}}'
  notify:
    - Rebuild MOTD

- name: Enable custom MOTD
  lineinfile:
    dest='/etc/ssh/sshd_config'
    regexp='^PrintMotd'
    line='PrintMotd yes'
    backrefs='yes'
  notify:
    - Restart SSH
