---
- name: Set timezone
  timezone:
    name: Europe/London

- name: Update apt cache
  apt:
    update-cache='yes'

- name: Install firewall
  apt:
    name='ufw'
    state='present'

- name: Open ports and enable firewall
  ufw:
    port='22'
    rule='allow'
    state='enabled'

- name: Install Fail2ban
  apt:
    name='fail2ban'
    state='present'

- name: Ensure Fail2ban is running
  service:
    name='fail2ban'
    state='started'

- name: Install boot notification script
  template:
    src='rc.local.j2'
    dest='/etc/rc.local'

- name: Install update script
  template:
    src='update.sh'
    dest='/home/{{user}}/update.sh'
    owner='{{user}}'
    group='{{user}}'
    mode='0764'

- name: Install general tools
  apt:
    name='{{item}}'
    state='present'
  with_items:
    - git
    - language-pack-en

- name: Install unattended upgrades
  apt:
    name='unattended-upgrades'
    state='present'

- name: Configure unattended-upgrades
  copy:
    dest='/etc/apt/apt.conf.d/20auto-upgrades'
    src='unattended-upgrades.conf'

- name: Create sudo success file
  copy:
    content=""
    dest='/home/{{user}}/.sudo_as_admin_successful'
    owner='{{user}}'
    group='{{user}}'
    mode='0644'
