---
- name: Load host variables
  include_vars: "sites/{{ ansible_hostname }}.yml"

- name: Create root web server directory
  file:
    path="/var/www"
    state=directory
    owner="www-data"
    group="www-data"
    mode=0755

- name: Create directory for deploy keys
  file:
    path="/var/www/.ssh"
    state=directory
    owner="www-data"
    group="www-data"
    mode=0700

- name: Copy Bitbucket deploy key
  copy:
    dest="/var/www/.ssh/deploy.id_rsa"
    content="{{ bitbucket_deploy_key }}"
    mode=0600
  become_user: www-data

- name: Create SSH config file
  copy:
    dest="/var/www/.ssh/config"
    content="IdentityFile ~/.ssh/deploy.id_rsa"
    owner="www-data"
    group="www-data"
    mode=0664
  become_user: www-data

- name: Fetch git repositories
  git:
    repo="{{ item.repo }}"
    version="{{ item.branch | default('master') }}"
    dest="/var/www/{{ item.url }}"
    depth=1
    accept_hostkey=yes
  become_user: www-data
  with_items: "{{ sites }}"
  when: item.repo is defined
