---
- name: Add PHP repository
  apt_repository: repo="ppa:ondrej/php"

- name: Install PHP packages
  apt:
    name={{ item }}
    state=latest
  with_items:
    - php{{ php_version }}-cli
    - php{{ php_version }}-curl
    - php{{ php_version }}-fpm
    - php{{ php_version }}-gd
    - php{{ php_version }}-mysql
    - php{{ php_version }}-zip
  notify:
    - Restart PHP-FPM

- name: Disable CGI file path fixing
  lineinfile:
    dest="/etc/php/{{ php_version }}/fpm/php.ini"
    regexp="^;cgi.fix_pathinfo=1"
    line="cgi.fix_pathinfo=0"
    backrefs=yes
  notify:
    - Restart PHP-FPM

- name: Disable PHP X-Powered-By header
  lineinfile:
    dest="/etc/php/{{ php_version }}/fpm/php.ini"
    regexp="^expose_php = On"
    line="expose_php = Off"
    backrefs=yes
  notify:
    - Restart PHP-FPM

- name: Name application for NewRelic
  lineinfile:
    dest="/etc/php/{{ php_version }}/fpm/php.ini"
    line="newrelic.appname = {{ ansible_hostname }}"
  notify:
    - Restart PHP-FPM

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  become: yes
  args:
    warn: no # Disable the warning about using cURL
    creates: /usr/local/bin/composer
