---
- name: Install prerequisites
  apt:
    name='{{item}}'
    state='present'
  with_items:
  - 'apt-transport-https'
  - 'ca-certificates'

- name: Fetch Docker apt-key
  apt_key:
    keyserver='p80.pool.sks-keyservers.net'
    id='58118E89F3A912897C070ADBF76221572C52609D'

- name: Add Docker source to source list
  copy:
    content='deb https{{':'}}//apt.dockerproject.org/repo ubuntu-trusty main'
    dest='/etc/apt/sources.list.d/docker.list'
    force=yes

- name: Install Docker engine
  apt:
    name='{{item}}'
    state='present'
    update-cache='yes'
  with_items:
  - 'docker-engine'
  notify:
  - Start Docker

- name: Add user to docker group
  user:
    name='{{user}}'
    groups='docker'
    append=yes
