---
- name: Set up user account and secure SSH
  become: yes
  hosts: all
  gather_facts: no
  pre_tasks:
     - name: 'install python2'
       raw: sudo apt-get -y install python-minimal
  roles:
    - user
    - ssh
  vars:
    ansible_ssh_user: root
