---
- name: Set up user account and disable root
  hosts: all
  roles:
    - user
  vars:
    ansible_user: root
  tags: user
  handlers:
  - include: handlers/handlers.yml

- name: Secure SSH
  hosts: all
  roles:
    - ssh
  vars:
    ansible_user: root
  tags: ssh
  handlers:
  - include: handlers/handlers.yml
