---
- name: common
  hosts: all
  become: yes
  roles:
    - common
  tags: common

- name: aesthetic
  hosts: all
  become: yes
  roles:
    - aesthetic
  tags: aesthetic

- name: docker
  hosts: nodes
  become: yes
  roles:
    - docker
  tags: docker

# - name: proxy
#   hosts: nodes
#   become: yes
#   roles:
#     - proxy
#   tags: proxy
