---
- name: Apply common configuration
  hosts: all
  become: yes
  roles:
    - common
  tags: common

- name: Apply aesthetic configuration
  hosts: all
  become: yes
  roles:
    - aesthetic
  tags: aesthetic
