---
- name: common
  hosts: all
  become: yes
  roles:
    - common
  tags: common

- name: aesthetic
  hosts: all
  become: yes
  roles:
    - aesthetic
  tags: aesthetic

- name: redis
  hosts: redis
  become: yes
  roles:
    - redis
  tags: redis
