---
- name: Apply common configuration
  hosts: all
  become: yes
  roles:
    - common
  tags: common
  handlers:
  - include: handlers/handlers.yml

- name: Apply aesthetic configuration
  hosts: all
  become: yes
  roles:
    - aesthetic
  tags: aesthetic
  handlers:
  - include: handlers/handlers.yml
