---

- hosts: all
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: aesthetic, tags: aesthetic }

- hosts: nodes
  become: yes
  roles:
    - { role: docker, tags: docker }
#   - { role: proxy, tags: proxy }
