---

- hosts: all
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: aesthetic, tags: aesthetic }

- hosts: nodes
  become: yes
  roles:
    - { role: php,      tags: php       }
    - { role: nginx,    tags: nginx     }
    - { role: ci,       tags: ci        }
#   - { role: mysql,    tags: mysql     }
    - { role: redis,    tags: redis     }
    - { role: newrelic, tags: newrelic  }
#   - { role: docker,   tags: docker    }
#   - { role: proxy,    tags: proxy     }
