---
- name: Load host variables
  include_vars: "sites/{{ ansible_hostname }}.yml"

- name: Create CI user
  user:
    name='ci'
    home='/src'
    password='{{ ci_crypted_password }}'
    shell='/bin/bash'
    state='present'
    update_password='on_create'

- name: Create directory for deploy keys
  file:
    path="/src/.ssh"
    state=directory
    owner="ci"
    group="ci"
    mode=0700

- name: Create releases directories
  file:
    path="/var/www/{{ item.url }}/releases"
    state="directory"
    owner="www-data"
    group="www-data"
    mode=0755
  with_items: "{{ sites }}"

- name: Copy continuous integration public key
  copy:
    dest="/src/.ssh/authorized_keys"
    content="{{ ci_deploy_pub }}"
    owner="ci"
    group="ci"
    mode=0600

- name: Copy deploy script
  copy:
    src="deploy.sh"
    dest="/src/deploy.sh"
    owner="ci"
    group="ci"
    mode=0755

- name: Copy domain calculation script
  template:
    src="domains.sh"
    dest="/src/domains.sh"
    owner="ci"
    group="ci"
    mode=0755

- name: Allow execution of deploy script as www-data
  lineinfile:
    dest: "/etc/sudoers"
    state: present
    line: "ci ALL =(www-data) NOPASSWD: /src/extract.sh"
    validate: 'visudo -cf %s'
